package net.pandorramc.config.info;

public enum InfoType {

	STRING, INT, LONG, FLOAT, BYTE, SHORT, DOUBLE, CHAR, BOOLEAN, 
	SERIALIZABLE, LIST, ITEMSTACK, ITEMARRAY, LOCATION, POTIONLIST, MAP, BYTEARRAY, COLOR, VECTOR;
	
}
